### PR TITLE
Footer added

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
Description:

Footer added with logo and social icons, nav links, copyrights
Please add `hacktoberfest-accepted` label

Issue: #29 

Screenshot:
image

### CODE REVIEW

**Comment by aryamankha** [comment]
Can you change the color of the footer to match the rest of the design scheme? Gray, black, or purple background is probably best

**Comment by aryamankha** [comment]
Should be pretty easy to test out a few color options with Vivid's command palette. Command-K after selecting the footer component should let you try out bg colors very fast

**Comment by jsvigneshkanna** [comment]
@aryamankha 
Updated footer with black background and purple-500 top border

image

**Comment by aryamankha** [comment]
Perfect! Merging now

**Pull request merged**
